// Temporary mock data — will be replaced with Supabase queries

export const FARMS = [
  {
    id: 'sunrise-acres',
    name: 'Sunrise Acres',
    tagline: 'Pasture-raised eggs from happy hens',
    location: 'Bakersfield, CA',
    image: 'https://images.unsplash.com/photo-1500595046743-cd271d694e30?w=600&h=400&fit=crop',
    rating: 4.9,
    reviews: 47,
    featured: true,
    categories: ['eggs'],
    about: 'Third-generation family farm raising heritage breed chickens on open pasture. Our girls roam freely, eating bugs, grass, and organic feed. You can taste the difference.',
    products: [
      { id: 1, name: 'Farm Fresh Eggs', description: 'One dozen large brown eggs', price: 8, unit: 'dozen', subscription: true },
      { id: 2, name: 'Jumbo Eggs', description: 'Extra large eggs, perfect for baking', price: 10, unit: 'dozen', subscription: true },
      { id: 3, name: 'Duck Eggs', description: 'Rich, creamy duck eggs', price: 12, unit: 'half dozen', subscription: false },
    ],
    delivery: ['Bakersfield', 'Oildale', 'Rosedale'],
    pickup: 'Saturday 8am-12pm at farm stand',
  },
  {
    id: 'green-valley-micro',
    name: 'Green Valley Microgreens',
    tagline: 'Nutrient-dense greens grown with care',
    location: 'Shafter, CA',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop',
    rating: 4.8,
    reviews: 31,
    featured: true,
    categories: ['microgreens', 'vegetables'],
    about: 'We grow over 15 varieties of microgreens in our climate-controlled greenhouse. Harvested fresh the morning of delivery for maximum nutrition and flavor.',
    products: [
      { id: 4, name: 'Microgreens Mix', description: "Chef's blend of sunflower, pea, and radish", price: 8, unit: '4oz', subscription: true },
      { id: 5, name: 'Sunflower Shoots', description: 'Nutty, crunchy sunflower microgreens', price: 6, unit: '2oz', subscription: true },
      { id: 6, name: 'Spicy Mix', description: 'Radish, mustard, and arugula micros', price: 7, unit: '2oz', subscription: false },
    ],
    delivery: ['Bakersfield', 'Shafter', 'Wasco'],
    pickup: "Wednesday & Saturday at Bako Farmer's Market",
  },
  {
    id: 'honey-hollow',
    name: 'Honey Hollow Apiary',
    tagline: 'Raw, unfiltered local honey',
    location: 'Arvin, CA',
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&h=400&fit=crop',
    rating: 5.0,
    reviews: 28,
    featured: false,
    categories: ['honey'],
    about: 'Our bees forage on wildflowers, citrus, and almond blossoms across Kern County. Each batch reflects the unique terroir of our region.',
    products: [
      { id: 7, name: 'Wildflower Honey', description: 'Multi-floral raw honey', price: 14, unit: 'pint', subscription: true },
      { id: 8, name: 'Honeycomb', description: 'Pure comb straight from the hive', price: 18, unit: '12oz', subscription: false },
    ],
    delivery: ['Bakersfield', 'Arvin', 'Lamont'],
    pickup: 'By appointment',
  },
  {
    id: 'valley-aquaponics',
    name: 'Valley Aquaponics',
    tagline: 'Sustainable shrimp & greens',
    location: 'Bakersfield, CA',
    image: 'https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=600&h=400&fit=crop',
    rating: 4.7,
    reviews: 19,
    featured: true,
    categories: ['seafood', 'vegetables'],
    about: 'Closed-loop aquaponics system raising Pacific white shrimp and leafy greens. Zero waste, zero antibiotics, incredible freshness.',
    products: [
      { id: 9, name: 'Fresh Shrimp', description: 'Live or flash-frozen, your choice', price: 18, unit: 'lb', subscription: true },
      { id: 10, name: 'Butter Lettuce', description: 'Hydroponically grown, no soil', price: 4, unit: 'head', subscription: true },
    ],
    delivery: ['Bakersfield'],
    pickup: 'Friday 4pm-7pm',
  },
]

export const CATEGORIES = [
  { id: 'eggs',        name: 'Eggs',        color: '#E8B86D' },
  { id: 'vegetables',  name: 'Vegetables',  color: '#7CB342' },
  { id: 'microgreens', name: 'Microgreens', color: '#43A047' },
  { id: 'honey',       name: 'Honey',       color: '#FFB300' },
  { id: 'seafood',     name: 'Seafood',     color: '#4FC3F7' },
  { id: 'fruit',       name: 'Fruit',       color: '#EF5350' },
]
